### ISSUE TITLE
dotaz

### ISSUE THREAD

**Issue by PaKr123** [tenhobi/ama#10]
Ahoj, reaguji na tvoji výzvu u jednoho z článků na IT network a chci se tě teda na něco zeptat. Mám základy html a css. Na IT network jsem dokončil tutoriál jak psát moderní web a teď se chci zeptat co by jsi doporučoval dál? Nebo spíš jaký je prosim tě rozdíl mezi PHP a JavaScript? Co každé na webu dělá? A webové stránky se tedy skládají hlavně z html a css - což je jejich kostra a PHP a JavaScriptem se doplňují různé aplikace a interaktivní prvky? Je tomu tak? :)
Díky za odpověď :)

**Comment by tenhobi** [comment]
**HTML** a **CSS** jsou základní jazyky pro web, resp. pro uživatelské prostředí - to, co vidíš.

**Javascript** se používá pro interakci v rámci uživatelského prostředí. Např. když klikneš na položku v menu, plynule ti stránka sroluje na danou sekci; složité animace (animace se dají z části dělat i v CSS); slideshow atp.

**PHP** se používá pro generování webů, resp. jeho sestavováním. PHP je nutné provozovat na serveru, odkud má také přístup k URL, nějakým informacím o uživateli atp. Na základě URL se určitým způsobem se pak vždy sestaví daná stránka - složitost nehraje roli, to už je na daném algoritmu. Je nutné si uvědomit, že PHP (resp. technologie okolo něj) pracuje v rámci požadavků, tedy pro každou změnu musíš vytvořit nový požadavek (dalo by se přirovnat k refreshi prohlížeče), který PHP zpracuje a znovu vygeneruje stránku.

---

Jelikož už máš díky kurzu základy HTML a CSS, doporučoval bych začít s Javascriptem nebo PHP. Pokud se chceš zaměřit na uživatelské prostředí - to co vidíš -, jdi do Javascriptu (dráha Front Endu); pokud se chceš zaměřit na sestavování/generování stránek, jdi do PHP (dráha Back Endu).

Nedá se říci, co je více "prestižní" nebo více placené. Záleží vždy na tvých zkušenostech a hlavně na tom, co umíš. Také je to o tom, co tě baví více. :-) 

_Možnosti PHP / JS se v dnešní době docela i dají srovnat (+-), kdy můžeš posílat AJAX požadavky (z JS do PHP bez nutnosti refreshe), vytvářet různé spojení mezi serverem a prohlížečem atp._

---

PHP - redakční systém
JS - interaktivní hry, weby...
