### ISSUE TITLE
Sublime Text 3 - jokoceres

### ISSUE THREAD

**Issue by jokoceres** [tenhobi/ama#14]
Dobry den.
 Chcem Vas poprosit o informaciu o použivani uvedeneho editoru. Napr. doporucene pluginy=packages - napr. ten, ktory doplna automaticky text tagu, nejaké zakladne navody, ... alebo ako pridat moznost prehliadania vysledku zdrojoveho kodu v samotnom Sublime, atd...
                  Dakujem   Joko

**Comment by tenhobi** [comment]
Různé info o pluginech musíš sám najít na https://packagecontrol.io - tj. přímo v dokumentaci pluginu. Případně se kouknout do klávesových zkratek přímo v editoru.

Např. pro ColorPicker najdeš tuto stránku https://packagecontrol.io/packages/ColorPicker, kde máš níže popsáno co a jak.

**Comment by jokoceres** [comment]
Zatial dakujem.

2016-08-31 9:49 GMT+02:00 Honza Bittner notifications@github.com:
