### ISSUE TITLE
nefunkční discord kanál

### ISSUE THREAD

**Issue by dzejkob-b** [tenhobi/ama#15]
Ahoj - vybavuju si tě z Discord kanálu FIT ČVUT, ze kterého mě to bohužel vykoplo. Chtěl jsem se dostat zpátky a už link nefunguje: https://discord.gg/K7rsAUX

Všechny další linky co najdu kdekoli na webu nejsou funkční. Bylo by možné poslat funkční odkaz?

Díky

(pardon že píšu sem - ale fakt nechci používat facebooky, twittery a jiné hrůzy - ten discrod jsem tak nějak zkousnul)

**Comment by tenhobi** [comment]
Ahoj, zkus https://discord.gg/DTmeWc2
