### ISSUE TITLE
Chybějící lekce kurzu Dart - OOP na itnetwork.cz

### ISSUE THREAD

**Issue by zoubeklukas** [tenhobi/ama#18]
Dobrý den,

v kurzu Objektově orientované programování v Dartu - Online kurz (https://www.itnetwork.cz/dart/oop) chybí poslední tři lekce.

Na stránce Česká Dart centrála - Výukové kurzy (https://www.itnetwork.cz/dart) je u kurzu uvedeno 16 lekcí, ale na stránce kurzu je jich zobrazeno jen 13. V 13. lekci již není možné dále pokračovat, byť v posledním odstavci je zmíněno co bude v další lekci.

Chtěl bych se zeptat, jestli se jedná o chybu nebo je to záměrné?

Jelikož mne kurz baví, tak bych ho rád dokončil celý. 

Již jsem psal na redakci skrze redakce@itnetwork.cz, ale zatím bez odpovědi.

Děkuji za odpověď.

![dart_oop_1](https://user-images.githubusercontent.com/68037887/113326317-cb58ec00-9319-11eb-921e-3f20bfabbe72.jpg)
![dart_oop_2](https://user-images.githubusercontent.com/68037887/113326326-cd22af80-9319-11eb-8b5e-11d9e9e965d7.jpg)
![dart_oop_3](https://user-images.githubusercontent.com/68037887/113326334-ceec7300-9319-11eb-97c3-66ce0e26180c.jpg)

**Comment by tenhobi** [comment]
Ahoj, počty sedí, v té sekci jsou 3x praktické cvičení. :-) 

Už delší dobu se aktivně neúčastním na ITnetworku, tudíž pokračování není a nebude. Nicméně, Dartu, Flutteru (multiplatformní framework využívající Dart) a podobně pořád aktivně používám, tudíž pokud by byl zájem nebo bys chtěl občas s něčím pomoci, můžeš mi napsat např. na Discordu a rád ti pomohu. :) https://discord.com/users/302127992258428929

**Comment by zoubeklukas** [comment]
Ahoj, to se moc omlouvám. Nějak jsem přehlédl, že se cvičení do toho nepočítají. Hledal jsem důvod, proč je na konci 13. lekce  zmínka o tom, co bude v další lekci a další lekce zde není a nějak jsem si toto dal dohromady. Ještě jednou se omlouvám.

Děkuji za nabídku a určitě ji rád v budoucnu využiji :-) . Zmíněný URL odkaz se ale zdá být nefunkční. Přesměruje mne na stránku pro přihlášení a když tedy jsem přihlášen na Discordu, tak mne přesměruje na https://discord.com/channels/@me , což je moje úvodní stránka. S Discord nemám zkušenosti.  Pomohl bys mi? Můj Discord zoublu #0648

**Comment by tenhobi** [comment]
Přesměrovat by to mělo, ale mělo by to ukázat ještě okno se mnou. Nevadí. V tom případě si mě přidej :) tenhobi#3744
