### ISSUE TITLE
Ultimate question

### ISSUE THREAD

**Issue by janbarasek** [tenhobi/ama#19]
Can I really ask you anything?

**Comment by tenhobi** [comment]
:D Sure, I guess.

**Comment by janbarasek** [comment]
What is meaning of life?

**Comment by tenhobi** [comment]
The obvious answer is 42, dunno if that is the answer to your question tho. 😁😂

**Comment by janbarasek** [comment]
```
X^3 + Y^3 = Z^3
```

Can you find the integers `X`, `Y` and `Z`, for it works?

**Comment by tenhobi** [comment]
Sure, it works for inputs 0, 0, 0. 

![](https://media3.giphy.com/media/K2MbdWVYVV3Tq/giphy.gif)

**Comment by janbarasek** [comment]
Wow, you are sooo smart!

And can you find solution, if x, y, z > 2?

**Comment by TouchstoneTheDev** [comment]
@janbarasek awesome readme! @tenhobi incoming
