### ISSUE TITLE
What's the most difficult thing about being a web developer today?

### ISSUE THREAD

**Issue by sindresorhus** [tenhobi/ama#2]

**Comment by tenhobi** [comment]
Well, I think you have to know a lot of tools, languages, frameworks, libraries, preprocessors... For example on my project I use things like HTML(5), CSS(3), JavaScript, jQuery, AngularJS, (Dart - not anymore), little bit of CoffeeScript, npm, bower, gulp, Sass, PHP, Polymer, SQL...

Of course I can use only "4 main" languages which are (for me) HTML, CSS, JS and PHP, but w/o some others like, for example, Sass is development a lot more difficult.
