### ISSUE TITLE
internships/traineeship

### ISSUE THREAD

**Issue by TouchstoneTheDev** [tenhobi/ama#20]
Heyo any internships/traineeship/mentorship/Opensource contri available in/for Flutter Development ?!

**Comment by tenhobi** [comment]
I am really not sure what you are asking about. However, currently I cannot help you with internships/traineeship/mentorship.

**Comment by TouchstoneTheDev** [comment]
Flutter internship @netglade :)

**Comment by tenhobi** [comment]
Just like I previously wrote, I am not sure I can help you with that. Especially since you didn't provide any valuable info such as if you are Czech or not etc. You can text me on Discord (tenhobi).
