### ISSUE TITLE
Who is the best pony?

### ISSUE THREAD

**Issue by mollikka** [tenhobi/ama#5]

**Comment by tenhobi** [comment]
From My Little Pony? 

I like the whole 6-team (+ Spike). But well, I like most Twilight Sparkle (for her awesome magic and clever) and Pinkie Pie (for her cutest and party spirit). :)

![](http://media.giphy.com/media/RBLyUtigywgrm/giphy.gif)

**Comment by mollikka** [comment]
Good choices :)
